# Get all notes
GET http://localhost:3001/notes HTTP/1.1
Content-Type: application/json

POST http://localhost:3001/notes HTTP/1.1
Content-Type: application/json

{
  "description": "notes test"
}

PUT http://localhost:3001/notes HTTP/1.1
Content-Type: application/json

{
  "description": "notes test"
}

DELETE http://localhost:3001/notes HTTP/1.1
Content-Type: application/json


# Get all users
GET http://localhost:3001/users HTTP/1.1
Content-Type: application/json

POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
  "description": "user test"
}

PUT http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
  "description": "New item"
}

DELETE http://localhost:3001/users HTTP/1.1
Content-Type: application/json